version: '3'
services:
  samba:
    container_name: samba
    image: samba:v1
    build:
      context: .
    volumes:
      - ./share:/share
      - ./smb.conf:/etc/samba/smb.tmpl
    ports:
      - 445:445
    environment:
      - "SMB_USER=share"
      - "SMB_PASSWORD=1234"
      - "SMB_NAME=shared"
      - "PUID=1000"
      - "PGID=1000"
